name: Tests
on: [push, pull_request]

jobs:
  tests:
    name: ${{ matrix.cmd }} on ${{ startsWith(matrix.os, 'macos-') && 'macOS' || startsWith(matrix.os, 'windows-') && 'Windows' || 'Linux' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python: "3.10", os: ubuntu-latest, cmd: "test.py310:test" }
          - { python: "3.10", os: windows-latest, cmd: "test.py310:test" }
          - { python: "3.10", os: macos-latest, cmd: "test.py310:test" }
          - { python: "3.11", os: ubuntu-latest, cmd: "test.py311:test" }
          - { python: "3.12", os: ubuntu-latest, cmd: "test.py312:test" }
          - { python: "3.9", os: ubuntu-latest, cmd: "test.py39:test" }
          - { python: "3.8", os: ubuntu-latest, cmd: "test.py38:test" }
          - { python: "pypy-3.9", os: ubuntu-latest, cmd: "test.pypy39:test" }
          - { python: "3.10", os: ubuntu-latest, cmd: lint }
          - { python: "3.10", os: ubuntu-latest, cmd: typing }
          - { python: "3.10", os: ubuntu-latest, cmd: cov }
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
          cache-dependency-path: "**/pyproject.toml"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade hatch
      - name: Test
        run: hatch run ${{ matrix.cmd }}
